### ISSUE TITLE
Docker port mapping (to different port) breaks QuickPlot

### ISSUE THREAD

**Issue by jumpinjackie** [brucepc/mapguide#4]
Something you might want to document about this container (in the readme or elsewhere)

If using docker port mapping to a different port (eg. `docker run -p 80:8008 ...`), QuickPlot will break as while the initial POST to `PlotAsPDF.php` will work, that script needs to internally make a request to `GeneratePicture.php`, by constructing a URL relative to the `$_SERVER["SCRIPT_URI"]` of `PlotAsPDF.php`.

As `PlotAsPDF.php` was accessed through its external port (80), the URL constructed to `GeneratePicture.php` is invalid because the httpd server inside the container is still listening on 8008.

I don't know what tricks we can use in PHP to make QuickPlot work in this type of setup. The only workaround is to map to the same port number externally

**Comment by brucepc** [comment]
I've made some tests and they works like a charm, could you help to produce the bug?

1. To produce the bug I've used [Sheboygan.mgp](http://download.osgeo.org/mapguide/releases/2.0.0/samples/Sheboygan.mgp);    
2. created a new ApplicationDefinition;    
3. running the images as docker --rm -ti -p 8088:8008 brucepc/mapguide;     
4. acessing the system throuth the host address that the container can reach 172.17.0.1 or hostname that the container could resolve mapguide.local registered in a local dnsmasq

**Comment by jumpinjackie** [comment]
I've been trying to spin up demo docker containers for [mapguide-react-layout](https://github.com/jumpinjackie/mapguide-react-layout) inside [play-with-docker](http://labs.play-with-docker.com/) using your docker image as the base.

Everything but the QuickPlot works fine. QuickPlot will only work if you explicitly tack on the `8008` port number to the PWD-generated host name.

**Comment by brucepc** [comment]
great project!
I made a test, I've followed the Demo.md instructions and change port to 80:8008 
as results below...   
![screenshot-20170905110347-1920x1079](https://user-images.githubusercontent.com/1097625/30067829-ec1a8bc8-9229-11e7-91d9-ce0662a45205.png)

**Comment by jumpinjackie** [comment]
Yep, your solution of just using `80:8008` works.
